production: &production
  adapter: redis
  url: redis://localhost:6379/1
staging: &staging
  adapter: redis
  url: redis://localhost:6379/1
development: &development
  adapter: redis
  url: redis://localhost:6379/1
